---
# handlers file for nginx
- name: check nginx configuration
  command: "nginx -t -c /etc/nginx/nginx.conf"

- name: restart service nginx
  service:
    name: nginx
    state: restarted
    enabled: yes
